baseurl = "http://scientistcafe.com"
languageCode = "en-us"
title = "Statistics = Science + Art"
theme = "hugo-xmin"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
    
[[menu.main]]
    name = "Blog"
    url = "/post"
    weight = 2
    
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3
[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 4
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 5
[[menu.main]]
    name = "Subscribe"
    url = "/index.xml"

[params]
    description = "A Website about Data Science"
    author = "Hui Lin"
    footer = "&copy; [Hui Lin](http://linhui.org) 2017 -- 2018 | [Github](https://github.com/happyrabbit) | [Twitter](https://twitter.com/gossip_rabbit)"
